version: '3'

services:
  zju_ai_backend:
    image: 127.0.0.1:5000/zsyh/zju_ai_backend
    hostname: zju_ai_backend
    ports:
    - 4800:4800
    build:
      context: ..
      dockerfile: docker/Dockerfile
